### ISSUE TITLE
404 error when clicking link "Getting Started"

### ISSUE THREAD

**Issue by tubbi12** [biga-ahk/biga.ahk#1]
Hi,
your Github "Getting Started" link is broken: [https://github.com/biga-ahk/biga.ahk/blob/master/getting-started](url)

**Comment by Chunjee** [comment]
#https://github.com/biga-ahk/biga.ahk/commit/d7076bc5a7dd65a7e1c429d0837f00a8cf819f47

Made link more compatible. Thanks.
