### ISSUE TITLE
indexOf breaks for objects

### ISSUE THREAD

**Issue by JMPSequeira** [biga-ahk/biga.ahk#2]
Don't know if this is by design or not but I found the result surprising.

OS: Windows 10 Professional
Version: 1.1.33.09

Code:
```autohotkey
global A := biga
obj:= {}
arr:=[obj]
res:=A.indexOf(arr, obj)
```
Expected: 1
Actual: -1

**Comment by Chunjee** [comment]
I was not able to duplicate this

```autohotkey
obj := {}
arr := [obj]
msgbox, % A.indexOf(arr, obj)
; => 1


obj := {}
arr := [{"key": "value"}, obj]
msgbox, % A.indexOf(arr, obj)
; => 2

**Comment by JMPSequeira** [comment]
Hey sorry for the late reply.

The problem was due to no initialization. I was using the class reference has the `global A`, and so this line on the map method would evaluate to false:
`if (this.startsWith(param_iteratee.name, this.base.__Class ".")) { ;if starts with "biga."`
