### ISSUE TITLE
Publish as an ahkpm package?

### ISSUE THREAD

**Issue by joshuacc** [biga-ahk/biga.ahk#7]
Hi @Chunjee. I'm wondering if you'd be interested in publishing Big A as an ahkpm package?

ahkpm is a package manager built specifically for AutoHotkey libraries.

- Repo: https://github.com/joshuacc/ahkpm
- Docs: https://ahkpm.dev/

I've written a [guide on how to publish ahkpm packages](https://ahkpm.dev/docs/guides/publishing/) and likely wouldn't take much time at all.

The main thing I noticed that you might need to change is to start tagging releases on the [other Big A repo](https://github.com/Chunjee/biga.ahk) with the version number of the release.

**Comment by Chunjee** [comment]
This is not a priority right now.
