### ISSUE TITLE
Awesome package!

### ISSUE THREAD

**Issue by drventure** [biga-ahk/biga.ahk#8]
First off, great work on this!

I was looking for a AHK Sort function and just happened to stumble onto this. It's virtually Linq2AHK. Just all round excellent stuff.

One comment I thought I throw out.

The help site mentions include-ing ....\node_modules

Not sure why but that doesn't actually appear to be necessary.

Second, the include file for biga ends up being named "export.ahk", which is a bit odd.

I think it'd be better to simply call it biga.ahk

Then, users could throw it in their <Lib> folder and include it with just

#include <biga>

You might even go so far as to also include a small bit of global code at the end to automatically define a big A variable...

global
A := new biga()

Not sure about the last bit. Maybe some people would want it to stay user defined....

Anyway, great work again!
Darin

**Comment by Chunjee** [comment]
> You might even go so far as to also include a small bit of global code at the end to automatically define a big A variable...

in ahk v1; class names are automatically superglobal.
