### ISSUE TITLE
Can A.chunk() work with named (big?) array?

### ISSUE THREAD

**Issue by Gh0sTG0** [biga-ahk/biga.ahk#9]
Hi. For some reasons I need to name every item in array. Then I'm trying to chunk it, but things stuck.
Is that ok?
My code:
```
array := []
Loop 1200 ; some pseudo loop filling array with pseudo functions getting name and value
    array[get_name(A_Index)] := get_value(A_Index)

A := new biga()
MsgBox, % A.size(array) ; it works and shows me 1200 elements in array

Chunked := A.chunk(array, 50)
MsgBox, It just finished working with chunks ; I don't see this msgbox. Tried to leave things for some minutes and nothing happens.
```

**Comment by Chunjee** [comment]
.chunk returns an array of arrays
Msgbox does not display arrays.

Try .join instead, it returns a string.

**Comment by Gh0sTG0** [comment]
Oh, sorry for dull messaging.
I didn't try to _show me what's inside that array of arrays._
There's "chunked" as word, not as %chunked%. Just word to show. There can be "dog", "Hi", "Chunjee" there, it doesn't matter.
PS Fixed for clearer understanding.

**Comment by Chunjee** [comment]
Perhaps I do not understand the bug
I was not able to duplicate this issue with a big or large array.
```autohotkey
arr := []
loop, 1200 {
	arr.push(A_Index)
}

chunked := A.chunk(arr, 50)
msgbox, % A.print(chunked.pop())
; => [1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200]
```

I think you are having an issue because .chunk appears to be designed for linear arrays, if you have a keyed object like {hello: "world, foo: "bar"} it will not work at all.

**Comment by Gh0sTG0** [comment]
Ah, ok. Didn't find about keyed objects in description of .chunk. (yep, it not works on `array[name] := value`).
Thanks for answer.
